// invalidEmails.js
export const invalidEmails = {
  empty: [
    "",
    " ",
    "   ",
    "@",
    "@example.com",
    "user@",
    "userexample.com",
    "user@@example.com",
    "user@ example.com",
    "user@example .com",
    "user example@example.com",
    "user@exa mple.com",
    "user\t@example.com",
    "user\n@example.com",
    "user\r@example.com",
    "user@example\n.com",
    "user@example\r.com",
    "user@\nexample.com",
    "user@\rexample.com",
    "user@\texample.com",
    "user@example\t.com",
    "user@example\r\n.com",
    "user@\r\nexample.com",
    "user @example.com",
    " user@example.com",
    "user@example.com ",
    " user@example.com ",
    "user@.com",
    "user@..com",
    "user@com."
  ],

  dotErrors: [
    ".user@example.com",
    "user.@example.com",
    "user..name@example.com",
    "user...name@example.com",
    "user..@example.com",
    "user@example..com",
    "user@example...com",
    "user@example.com.",
    "user@example..com",
    "user@.example.com",
    "user@..example.com",
    "user@exa..mple.com",
    "user@ex..ample.com",
    "user@exam..ple.com",
    "user@.example..com",
    "user.@.example.com",
    "user..@..example.com",
    "user...@example.com",
    "user@...example.com",
    "user@exam...ple.com",
    "user.@example..com",
    "user@.example.com.",
    "user@..example.com.",
    "user..name@domain..com",
    "user.name@domain..com",
    "user@domain..co",
    "user@domain.co.",
    "user@.domain.co",
    "user@domain..co.uk"
  ],

  invalidCharacters: [
    "user()< >@example.com",
    "user[]@example.com",
    "user,comma@example.com",
    "user:semicolon@example.com",
    "user:colon@example.com",
    "user<less>@example.com",
    "user>greater@example.com",
    "user\"quote@example.com",
    "user\\backslash@example.com",
    "user|pipe@example.com",
    "user{brace@example.com",
    "user}brace@example.com",
    "user space@example.com",
    "user\tname@example.com",
    "user\nname@example.com",
    "user\rname@example.com",
    "user@exa<mple.com",
    "user@exa>mple.com",
    "user@exa[mple.com",
    "user@exa]mple.com",
    "user@exa{mple.com",
    "user@exa}mple.com",
    "user@exa|mple.com",
    "user@exa\\mple.com",
    "user@exa,mple.com",
    "user@exa;mple.com",
    "user@exa:mple.com"
  ],

  quotedErrors: [
    "\"unclosed@example.com",
    "\"bad\"quote\"@example.com",
    "\"double\"\"quote\"@example.com",
    "\"escaped\\\"quote@example.com",
    "\"\"\"@example.com",
    "\" \"example.com",
    "\"test\"example.com",
    "\"test\"@@example.com",
    "\"test\"@",
    "\"test\"@.com",
    "\"test\"@example",
    "\"test\"@example..com",
    "\"test\"example@example.com",
    "\"test\"@example.com.",
    "\"test\"@.example.com",
    "\"test\"@exa mple.com",
    "\"test\"@\nexample.com",
    "\"test\"@\rexample.com",
    "\"test\"@\texample.com",
    "\"test\"@example\r.com",
    "\"test\"@example\n.com",
    "\"test\"@example\t.com",
    "\"test\"@example..com",
    "\"test\"@@example.com",
    "\"test\"@example@com",
    "\"test\"@example.com@"
  ],

  unicodeErrors: [
    "ação@exam ple.com",
    "用户@exa mple.com",
    "δοκιμή@exam\nple.com",
    "राम@exam\rple.com",
    "почта@exa\tmple.com",
    "用户@example..com",
    "用户@.example.com",
    "用户@example.com.",
    "用户@-example.com",
    "用户@example-.com",
    "用户@exa--mple.com",
    "用户@exa.-mple.com",
    "用户@exa-.mple.com",
    "用户@exa..mple.com",
    "用户@exa_mple.com",
    "用户@exa#mple.com",
    "用户@exa%mple.com",
    "用户@exa@mple.com",
    "用户@exa!mple.com",
    "用户@exa$mple.com",
    "用户@exa&mple.com",
    "用户@exa*mple.com",
    "用户@exa(mple.com",
    "用户@exa)mple.com",
    "用户@exa+mple.com",
    "用户@exa,mple.com",
    "用户@exa;mple.com",
    "用户@exa:mple.com"
  ],

  punycodeErrors: [
    "user@xn--.com",
    "user@xn--",
    "user@xn--com",
    "user@xn--example",
    "user@xn--example.",
    "user@xn--example-.com",
    "user@xn---example.com",
    "user@xn--example..com",
    "user@xn--example_.com",
    "user@xn--example#.com",
    "user@xn--example$.com",
    "user@xn--example@com",
    "user@xn--example!.com",
    "user@xn--example%.com",
    "user@xn--example^.com",
    "user@xn--example&.com",
    "user@xn--example*.com",
    "user@xn--example(.com",
    "user@xn--example).com",
    "user@xn--example+.com",
    "user@xn--example,.com",
    "user@xn--example;.com",
    "user@xn--example:.com",
    "user@xn--example..com",
    "user@xn--example.com."
  ],

  localhostErrors: [
    "user@localhost.",
    "user@.localhost",
    "user@local host",
    "user@local\nhost",
    "user@local\thost",
    "user@-localhost",
    "user@localhost-",
    "user@local_host",
    "user@local#host",
    "user@local@host",
    "user@local!host",
    "user@local$host",
    "user@local%host",
    "user@local^host",
    "user@local&host",
    "user@local*host",
    "user@local(host",
    "user@local)host",
    "user@local+host",
    "user@local,host",
    "user@local;host",
    "user@local:host",
    "user@localhost..",
    "user@localhost..local",
    "user@localhost..com",
    "user@localhost.com.",
    "user@localhost..com"
  ]
};
