// invalidEmails.js
// Comprehensive test suite for RFC 6531 email validation
// Each category contains examples of specific types of violations

export const invalidEmails = {
  // 1️⃣ ERROS ESTRUTURAIS (sintaxe básica)
  structureErrors: [
    "plainaddress",
    "@no-local-part.com",
    "no-at-symbol.com",
    "user@@example.com",
    "user@@@example.com",
    "user@",
    "@example.com",
    "@@",
    "@",
    "user",
    "user@.com",
    "user@domain@domain.com",
    "@user@example.com",
    "user@example.com@",
    "@user@example.com@",
    "user name@example.com",
    "user@domain com",
    " @example.com",
    "user@ ",
    "@ ",
    " @ ",
    "example.com",
    "user#example.com",
    "user%example.com",
    "user&example.com",
    "user*example.com",
    "user+example@",
    "@+example.com",
    "user@@",
    "@@domain.com",
    "user@domain@",
    "@domain@com",
    "user@@domain@@com",
    "text before user@example.com",
    "user@example.com text after",
    "prefix user@example.com",
    "user@example.com suffix",
    "<<user@example.com>>",
    "(user@example.com)",
    "[user@example.com]",
    "{user@example.com}",
    "user @example.com",
    "user@ example.com",
    "user @ example.com",
    " user@example.com ",
    "user@example.com\n",
    "\nuser@example.com",
    "user@\nexample.com",
    "user\n@example.com",
    "@@@",
    "user@domain@domain@com",
    "multiple@@signs@domain.com",
  ],

  // 2️⃣ ERROS DE PONTO (.)
  dotErrors: [
    ".user@example.com",
    "user.@example.com",
    "user..name@example.com",
    "user...name@example.com",
    ".@example.com",
    "..@example.com",
    "user.@domain.com",
    ".user.name@example.com",
    "user.name.@example.com",
    "user@.example.com",
    "user@example.com.",
    "user@.domain.com",
    "user@domain..com",
    "user@domain...com",
    "user@.example.",
    "user@..example.com",
    "user@example..com",
    ".user.@example.com",
    "..user@example.com",
    "user..@example.com",
    "user@example..",
    "user@.example.com.",
    ".@.",
    "...@example.com",
    "user@...example.com",
    "user@example.com...",
    "user.name..surname@example.com",
    "user..name..surname@example.com",
    ".user.name.surname@example.com",
    "user.name.surname.@example.com",
    "user@domain.com..",
    "user@.domain.com.",
    "user@..domain.com",
    "user@domain..com.",
    "user@.domain..com",
    ".user@.example.com",
    "user.@example..com",
    "..user..@..example..com..",
    "user@domain.com..",
    "user@.sub.domain.com",
    "user@sub..domain.com",
    "user@sub.domain..com",
    "user@.sub.domain.com.",
    ".@domain.com",
    "user@domain.com.",
    "user@.domain.com",
    "user@domain..com",
    ".user.@.domain.com",
    "user..name@domain..com",
    "...user...@...domain...com...",
    ".........@example.com",
  ],

  // 3️⃣ ERROS DE HÍFEN (-)
  hyphenErrors: [
    "user@-example.com",
    "user@example-.com",
    "user@-example-.com",
    "user@domain.-example.com",
    "user@domain.example-.com",
    "user@-domain.example.com",
    "user@domain-.example.com",
    "user@ex-ample-.com",
    "user@-ex-ample.com",
    "user@--example.com",
    "user@example--.com",
    "user@--.com",
    "user@--domain--.com",
    "user@domain.com-",
    "user@-domain.com-",
    "user@-.example.com",
    "user@example.-.com",
    "user@-.-.com",
    "user@-sub.domain.com",
    "user@sub-.domain.com",
    "user@sub.-domain.com",
    "user@sub.domain-.com",
    "user@-sub-domain.com",
    "user@sub-domain-.com",
    "user@-subdomain-.com",
    "user@----example.com",
    "user@example----.com",
    "user@-example-domain.com",
    "user@example-domain-.com",
    "user@-.domain-.com",
    "user@-a.example.com",
    "user@a-.example.com",
    "user@example.-com",
    "user@-example.-com",
    "user@-.-",
    "user@-.-.-.com",
    "user@domain.-.-com",
    "user@-domain.-com",
    "user@-.example-.com",
    "user@--.example--.com",
    "user@---example---.com",
    "user@example.com--",
    "user@--example.com--",
    "user@-.sub.domain.com",
    "user@sub.-.domain.com",
    "user@sub.domain.-.com",
    "user@-a-.-b-.com",
    "user@-abc-.-def-.com",
    "user@test.-domain.com",
    "user@test.domain-.com",
  ],

  // 4️⃣ CARACTERES INVÁLIDOS NO LOCAL-PART
  invalidCharacters: [
    "user<name@example.com",
    "user>name@example.com",
    "user<>@example.com",
    "user(name@example.com",
    "user)name@example.com",
    "user()@example.com",
    "user[name@example.com",
    "user]name@example.com",
    "user[]@example.com",
    "user{name@example.com",
    "user}name@example.com",
    "user{}@example.com",
    "user|name@example.com",
    "user\\name@example.com",
    "user,name@example.com",
    "user;name@example.com",
    "user:name@example.com",
    "user name@example.com",
    "user\tname@example.com",
    "user\nname@example.com",
    "user\rname@example.com",
    "user\"name@example.com",
    "user'name@example.com",
    "user`name@example.com",
    "user~name@example.com",
    "user!name!@example.com",
    "user#name@example.com",
    "user$name@example.com",
    "user%name@example.com",
    "user&name@example.com",
    "user*name@example.com",
    "user😀@example.com",
    "user❤️@example.com",
    "user🎉@example.com",
    "user👍@example.com",
    "user🔥@example.com",
    "user@😀example.com",
    "😀@example.com",
    "user\x00@example.com",
    "user\x01@example.com",
    "user\x1F@example.com",
    "user\x7F@example.com",
    "user<script>@example.com",
    "user()[]{}@example.com",
    "user\\ @example.com",
    "user\\\t@example.com",
    "user<>()<>@example.com",
    "user,;:@example.com",
    "user name space@example.com",
    "user\u0000@example.com",
    "user\u0001@example.com",
  ],

  // 5️⃣ ERROS EM QUOTED LOCAL-PART
  quotedErrors: [
    "\"user@example.com",
    "user\"@example.com",
    "\"user@example.com",
    "\"user\"name@example.com",
    "\"user@example.com",
    "user\"@example.com",
    "\"\"@example.com",
    "\"user name\"text@example.com",
    "text\"user name\"@example.com",
    "\"user name\" text@example.com",
    "\"user\\\"@example.com",
    "\"user\\\\\"@example.com",
    "\"user\n\"@example.com",
    "\"user\r\"@example.com",
    "\"user\r\n\"@example.com",
    "\"user\t\"@example.com",
    "\"user name@example.com",
    "user name\"@example.com",
    "\"user\"@\"example.com\"",
    "\"\"user\"\"@example.com",
    "\"user\"\"name\"@example.com",
    "\"user\\@example.com",
    "\"user\\\\@example.com",
    "\"user\\\\\\\"@example.com",
    "\"\"\"@example.com",
    "\"user name",
    "user name\"",
    "\"user name",
    "\"user\"middle\"name\"@example.com",
    "\"user\"@example.com\"extra",
    "extra\"user\"@example.com",
    "\"user\nname\"@example.com",
    "\"user\rname\"@example.com",
    "\"user\tname\"@example.com",
    "\"user\\nname\"@example.com",
    "\"user\\rname\"@example.com",
    "\"user\\tname\"@example.com",
    "\"@example.com",
    "@\"example.com\"",
    "\"user\"\"@example.com",
    "\"user\"@\"example.com",
    "\"user@\"example.com",
    "\"user name\\\"@example.com",
    "\"user name\\\\@example.com",
    "\"user\"name\"surname\"@example.com",
    "\"user\" \"name\"@example.com",
    "\"user\"\n@example.com",
    "\"user\"@\nexample.com",
    "\"user name\" @example.com",
    "\" user\"@example.com",
  ],

  // 6️⃣ UNICODE MALFORMADO
  unicodeErrors: [
    "userã@example.com",
    "user@exãmple.com",
    "usuário@example.com",
    "user@exëmple.com",
    "user@examplé.com",
    "üser@example.com",
    "user@ëxample.com",
    "user@example.cöm",
    "user@examplê.com",
    "usér@example.com",
    "user@éxample.com",
    "user@example.côm",
    "user\uFFFD@example.com",
    "user@example\uFFFD.com",
    "user\u200B@example.com",
    "user@example\u200B.com",
    "user\u200C@example.com",
    "user@example\u200C.com",
    "user\u200D@example.com",
    "user@example\u200D.com",
    "user\uFEFF@example.com",
    "user@example\uFEFF.com",
    "user@example.com\u200B",
    "user@example.com\u200C",
    "user@example.com\u200D",
    "user@example.com\uFEFF",
    "user@eχample.com",
    "user@examρle.com",
    "user@exаmple.com",
    "user@examрle.com",
    "user@еxample.com",
    "user@examplе.com",
    "user@ехample.com",
    "usеr@example.com",
    "uѕer@example.com",
    "user@example。com",
    "user@example．com",
    "user@example｡com",
    "user＠example.com",
    "user﹫example.com",
    "user@example،com",
    "user@example؛com",
    "user@example․com",
    "user@example‧com",
    "user@example⁃com",
    "user@example∙com",
    "user\u0301@example.com",
    "user\u0308@example.com",
    "user@exam\u0301ple.com",
    "user@exam\u0308ple.com",
  ],

  // 7️⃣ ERROS DE PUNYCODE
  punycodeErrors: [
    "user@xn--",
    "user@xn--.com",
    "user@xn--invalid",
    "user@xn--invalid.com",
    "user@xn--123",
    "user@xn--abc",
    "user@xn--xyz.com",
    "user@xn--..com",
    "user@xn--.xn--.com",
    "user@xn--domain.xn--",
    "user@xn--domain.xn--.com",
    "xn--user@example.com",
    "xn--user@xn--domain",
    "user@xn--domain.xn--invalid",
    "user@xn--!!!.com",
    "user@xn--###.com",
    "user@xn--$.com",
    "user@xn--%.com",
    "user@xn--&.com",
    "user@xn--*.com",
    "user@xn--ñ.com",
    "user@xn--@.com",
    "user@xn-- .com",
    "user@xn--\t.com",
    "user@xn--\n.com",
    "user@xn--domain.xn--tld",
    "user@xn--mixed-português.com",
    "user@português-xn--.com",
    "user@xn--português.com",
    "user@domain.xn--",
    "user@xn--.domain.com",
    "user@xn--sub.xn--.com",
    "user@xn--..xn--.com",
    "user@xn--..",
    "user@..xn--domain.com",
    "user@xn--domain..com",
    "user@xn--domain.com.xn--",
    "user@xn--domainمثال.com",
    "user@مثالxn--domain.com",
    "user@xn--мир.com",
    "user@мирxn--.com",
    "user@xn--世界.com",
    "user@世界xn--.com",
    "user@xn--domain.xn--invalid-punycode",
    "user@xn--a.xn--b",
    "user@xn--1.xn--2",
    "user@xn--!@#.com",
    "user@xn--🙂.com",
    "user@xn---.com",
    "user@xn-----.com",
  ],

  // 8️⃣ ERROS DE DOMÍNIO
  domainErrors: [
    "user@.com",
    "user@com",
    "user@domain",
    "user@domain.c",
    "user@domain.12345",
    "user@123.456.789.012",
    "user@domain.toolongtldtoolongtldtoolongtldtoolongtldtoolongtld",
    "user@verylongdomainnameverylongdomainnameverylongdomainnameverylongdomainname.com",
    "user@domainwithmorethan63charactersinasinglellabelsegmentwhichisnotallowed.com",
    "user@" + "a".repeat(64) + ".com",
    "user@domain." + "a".repeat(64),
    "user@" + "a".repeat(250) + ".com",
    "user@domain.com" + "a".repeat(240),
    "user@123",
    "user@123.456",
    "user@123.456.789",
    "user@123456789",
    "user@12345.com",
    "user@domain.123",
    "user@.123.com",
    "user@domain..123",
    "user@domain.com.123",
    "user@-.com",
    "user@domain.-",
    "user@-.-.com",
    "user@domain.-.com",
    "user@label" + "a".repeat(60) + ".com",
    "user@" + "verylonglabel".repeat(20) + ".com",
    "user@domain" + ".subdomain".repeat(30) + ".com",
    "user@" + "a.".repeat(130) + "com",
    "user@domain.invalidtldthatswaytoolong",
    "user@domain.t",
    "user@domain.123456",
    "user@domain.!@#",
    "user@domain.a b",
    "user@domain.a\tb",
    "user@domain.a\nb",
    "user@domain.a-",
    "user@domain.-a",
    "user@-domain.com",
    "user@domain-.com",
    "user@.domain.com",
    "user@domain.com.",
    "user@domain..com",
    "user@..domain.com",
    "user@domain...com",
    "user@...domain...com...",
    "user@domain com",
    "user@domain\tcom",
    "user@domain\ncom",
    "user@domain<>com",
    "user@domain()com",
    "user@domain[]com",
  ],

  // 9️⃣ LOCALHOST / AMBIENTE INTERNO
  localhostErrors: [
    "user@localhost.",
    "user@.localhost",
    "user@localhost..",
    "user@..localhost",
    "user@localhost..local",
    "user@.localhost.",
    "user@..localhost..",
    "user@[300.1.1.1]",
    "user@[999.999.999.999]",
    "user@[256.1.1.1]",
    "user@[1.256.1.1]",
    "user@[1.1.256.1]",
    "user@[1.1.1.256]",
    "user@[1.1.1]",
    "user@[1.1]",
    "user@[1]",
    "user@[1.1.1.1.1]",
    "user@192.168.1.1",
    "user@[192.168.1]",
    "user@[192.168]",
    "user@[192]",
    "user@[abcd:efgh::1]",
    "user@[::ffff:999.1.1.1]",
    "user@[::ffff:256.1.1.1]",
    "user@[2001:db8::gggg]",
    "user@[2001:db8::1::2]",
    "user@[2001:db8:::1]",
    "user@[:::]",
    "user@[::]",
    "user@[2001:db8]",
    "user@[fe80::1",
    "user@fe80::1]",
    "user@[fe80::1]]",
    "user@[[fe80::1]",
    "user@[]",
    "user@[.]",
    "user@[localhost]",
    "user@[.localhost]",
    "user@[localhost.]",
    "user@[127.0.0.1",
    "user@127.0.0.1]",
    "user@[127.0.0.1]]",
    "user@[[127.0.0.1]",
    "user@[ 127.0.0.1]",
    "user@[127.0.0.1 ]",
    "user@[ 127.0.0.1 ]",
    "user@[127 .0.0.1]",
    "user@[127. 0.0.1]",
    "user@[a.b.c.d]",
    "user@[domain.local]",
  ],

  // 🔟 ESPAÇOS E WHITESPACE INVISÍVEL
  spacingErrors: [
    " user@example.com",
    "user @example.com",
    "user@ example.com",
    "user@example.com ",
    " user@example.com ",
    "  user@example.com",
    "user  @example.com",
    "user@  example.com",
    "user@example.com  ",
    "user @example.com",
    "user@ example.com",
    "user @ example.com",
    "\tuser@example.com",
    "user\t@example.com",
    "user@\texample.com",
    "user@example.com\t",
    "\nuser@example.com",
    "user\n@example.com",
    "user@\nexample.com",
    "user@example.com\n",
    "\ruser@example.com",
    "user\r@example.com",
    "user@\rexample.com",
    "user@example.com\r",
    "\r\nuser@example.com",
    "user\r\n@example.com",
    "user@\r\nexample.com",
    "user@example.com\r\n",
    "user\u00A0@example.com",
    "user@\u00A0example.com",
    "user@example.com\u00A0",
    "\u00A0user@example.com",
    "user\u00A0name@example.com",
    "user@example\u00A0.com",
    "user@example.\u00A0com",
    "user\u200B@example.com",
    "user@example\u200B.com",
    "user@example.com\u200B",
    "\u200Buser@example.com",
    "user\u200C@example.com",
    "user@example\u200C.com",
    "user@example.com\u200C",
    "user\u200D@example.com",
    "user@example\u200D.com",
    "user@example.com\u200D",
    "user\uFEFF@example.com",
    "user@example\uFEFF.com",
    "user@example.com\uFEFF",
    "\u2003user@example.com",
    "user\u2003@example.com",
  ],

  // 1️⃣1️⃣ ERROS DE COMPRIMENTO
  lengthErrors: [
    // Local-part > 64 caracteres
    "a".repeat(65) + "@example.com",
    "user" + "a".repeat(61) + "@example.com",
    "verylongusernamethatshouldexceedthelimitofsixtyfourcharactersintotal@example.com",
    "a".repeat(70) + "@example.com",
    "a".repeat(100) + "@example.com",
    "usernamewithlots" + "a".repeat(50) + "@example.com",
    "a".repeat(64) + "x@example.com",
    "test." + "a".repeat(60) + "@example.com",
    "a".repeat(80) + "@example.com",
    "local" + "a".repeat(100) + "@example.com",
    
    // Domínio > 255 caracteres
    "user@" + "a".repeat(250) + ".com",
    "user@" + "subdomain.".repeat(30) + "example.com",
    "user@" + "a".repeat(256) + ".com",
    "user@" + "verylongsubdomain".repeat(20) + ".com",
    "user@" + "domain.".repeat(50) + "com",
    "user@" + "a.".repeat(100) + "com",
    "user@" + "x".repeat(300) + ".com",
    "user@" + "sub.".repeat(60) + "domain.com",
    "user@" + "a".repeat(240) + ".example.com",
    "user@" + "domain" + "a".repeat(250) + ".com",
    
    // Endereço total > 254 caracteres
    "a".repeat(50) + "@" + "b".repeat(200) + ".com",
    "user" + "a".repeat(40) + "@" + "domain" + "b".repeat(200) + ".com",
    "a".repeat(60) + "@" + "b".repeat(195) + ".com",
    "verylonguser@" + "verylongdomain".repeat(20) + ".com",
    "a".repeat(64) + "@" + "b".repeat(191) + ".com",
    "test@" + "a".repeat(250) + ".com",
    "user" + "x".repeat(50) + "@" + "domain" + "y".repeat(200) + ".com",
    "a".repeat(100) + "@" + "b".repeat(155) + ".com",
    "longlocal" + "a".repeat(50) + "@" + "longdomain" + "b".repeat(180) + ".com",
    "a".repeat(63) + "@" + "b".repeat(192) + ".com",
    
    // Label > 63 caracteres
    "user@" + "a".repeat(64) + ".com",
    "user@subdomain." + "a".repeat(64) + ".com",
    "user@" + "a".repeat(64) + ".example.com",
    "user@domain." + "a".repeat(64) + ".com",
    "user@" + "verylonglabelthatshouldexceedsixtyhrthreecharactersinlengthtotal.com",
    "user@sub." + "a".repeat(65) + ".domain.com",
    "user@" + "a".repeat(70) + ".example.com",
    "user@example." + "a".repeat(64) + ".com",
    "user@" + "label" + "a".repeat(60) + ".com",
    "user@" + "a".repeat(100) + ".domain.com",
    
    // Combinações múltiplas de violações de comprimento
    "a".repeat(65) + "@" + "b".repeat(256) + ".com",
    "user" + "a".repeat(80) + "@" + "domain" + "b".repeat(260) + ".com",
    "a".repeat(70) + "@" + "c".repeat(64) + ".example.com",
    "verylonglocal" + "x".repeat(60) + "@" + "verylongdomain" + "y".repeat(250) + ".com",
    "a".repeat(100) + "@" + "b".repeat(300) + ".com",
    "test" + "a".repeat(70) + "@" + "sub." + "b".repeat(250) + ".com",
    "user" + "x".repeat(90) + "@" + "y".repeat(64) + ".domain.com",
    "a".repeat(65) + "@" + "sub.".repeat(50) + "domain.com",
    "local" + "a".repeat(100) + "@" + "domain.".repeat(40) + "com",
    "a".repeat(64) + "x@" + "b".repeat(64) + "y.example.com",
  ],

  // 1️⃣2️⃣ ERROS "VISUALMENTE VÁLIDOS" (armadilhas)
  homographErrors: [
    "user＠example.com",
    "user@example․com",
    "user@example。com",
    "user@example｡com",
    "user﹫example.com",
    "user⁄example.com",
    "user∕example.com",
    "user⫽example.com",
    "user@exаmple.com",
    "user@examрle.com",
    "user@еxample.com",
    "user@ехample.com",
    "usеr@example.com",
    "uѕer@example.com",
    "user@example.сom",
    "user@example.cоm",
    "user@ехаmрlе.com",
    "user@eхample.com",
    "user@examplе.com",
    "user@ｅxample.com",
    "user@eⅹample.com",
    "user@examplе.com",
    "usеr@examplе.com",
    "user＠examplе.com",
    "user@example‧com",
    "user@example․com",
    "user@example∙com",
    "user@example⁃com",
    "user@example⸱com",
    "user@example꓾com",
    "user@example·com",
    "user@example‧com",
    "user@example՝com",
    "user@example᛫com",
    "user@example‥com",
    "user@example⋅com",
    "user@example⋯com",
    "user@example⸳com",
    "user＠еxamplе․com",
    "usеr＠еxamplе․com",
    "user@ехаmрlе․сom",
    "user@example.com\u200B",
    "user@example.com\u200C",
    "user@example.com\u200D",
    "user@example.com\uFEFF",
    "user\u200B@example.com",
    "user\u200C@example.com",
    "user\u200D@example.com",
    "user\uFEFF@example.com",
    "user@exam\u200Bple.com",
  ],

  // 1️⃣3️⃣ IP LITERAL INVÁLIDO
  ipLiteralErrors: [
    "user@[300.1.1.1]",
    "user@[999.999.999.999]",
    "user@[256.1.1.1]",
    "user@[1.256.1.1]",
    "user@[1.1.256.1]",
    "user@[1.1.1.256]",
    "user@[1.1.1]",
    "user@[1.1]",
    "user@[1]",
    "user@[1.1.1.1.1]",
    "user@[...]",
    "user@[.1.1.1]",
    "user@[1..1.1]",
    "user@[1.1..1]",
    "user@[1.1.1.]",
    "user@192.168.1.1",
    "user@[192.168.1.1",
    "user@192.168.1.1]",
    "user@[[192.168.1.1]]",
    "user@[ 192.168.1.1]",
    "user@[192.168.1.1 ]",
    "user@[192 .168.1.1]",
    "user@[abcd:efgh::1]",
    "user@[::ffff:999.1.1.1]",
    "user@[::ffff:256.1.1.1]",
    "user@[2001:db8::gggg]",
    "user@[2001:db8::1::2]",
    "user@[2001:db8:::1]",
    "user@[:::]",
    "user@[2001:db8]",
    "user@[fe80::1",
    "user@fe80::1]",
    "user@[fe80::1]]",
    "user@[[fe80::1]",
    "user@[2001:db8::1::1]",
    "user@[:::1]",
    "user@[::ffff:192.168.1.999]",
    "user@[::ffff:192.168.999.1]",
    "user@[::ffff:192.999.1.1]",
    "user@[::ffff:999.168.1.1]",
    "user@[2001:0db8:85a3::8a2e:0370:7334:extra]",
    "user@[2001:db8:85a3::8a2e:370k:7334]",
    "user@[IPv6:2001:db8::1]",
    "user@[v1.2001:db8::1]",
    "user@[IPv6:::1]",
    "user@[::ffff:192.168.1.1.1]",
    "user@[::192.168.1]",
    "user@[2001:db8::1:2:3:4:5:6]",
    "user@[2001:db8::]",
    "user@[:1]",
  ],

  // 1️⃣4️⃣ COMENTÁRIOS RFC INVÁLIDOS
  commentErrors: [
    "user(comment@example.com",
    "user)comment@example.com",
    "user(comment)incomplete@example.com",
    "user@(comment)example.com",
    "user@example(comment.com",
    "user@example.com(comment",
    "(comment)user@example.com",
    "user@example.com(comment)",
    "user(comment(nested))@example.com",
    "user((nested)@example.com",
    "user(nested))@example.com",
    "user@(example.com",
    "user@example.com(",
    "user@example.com)",
    "(user@example.com",
    ")user@example.com",
    "user(@example.com",
    "user)@example.com",
    "user@(example).com",
    "user@example(.com",
    "user@example).com",
    "user(comment)name@example.com",
    "user@example(comment)domain.com",
    "user(comment1)(comment2)@example.com",
    "user@(comment1)(comment2)example.com",
    "user(comment @example.com",
    "user comment)@example.com",
    "user( comment )@example.com",
    "user@( comment )example.com",
    "user(comment\n)@example.com",
    "user(comment\r)@example.com",
    "user(comment\t)@example.com",
    "user(comment\\)@example.com",
    "user(comment()@example.com",
    "user@example.com(comment1(comment2)",
    "user@example.com(comment1)comment2)",
    "user(()@example.com",
    "user())@example.com",
    "user((((@example.com",
    "user))))@example.com",
    "(((user)))@example.com",
    "user@(((example))).com",
    "user((comment)@example.com",
    "user(comment))@example.com",
    "user(comment1(comment2)@example.com",
    "user(comment1)comment2)@example.com",
    "(incomplete comment user@example.com",
    "user@example.com incomplete comment)",
    "user(comment@invalid)@example.com",
  ],
};